import { chromium } from '@playwright/test';
const [url] = process.argv.slice(2);
const browser = await chromium.launch();
const page = await browser.newPage();
const counts = { join: 0, leave: 0 };
page.on('websocket', (ws) => ws.on('framesent', (f) => { const p = String(f.payload); if (p.includes('"court:join"')) counts.join++; if (p.includes('"court:leave"')) counts.leave++; }));
await page.goto(url);
await page.waitForTimeout(4000);
console.log(JSON.stringify(counts));
await browser.close();
