import { chromium } from '@playwright/test';
const [url] = process.argv.slice(2);
const browser = await chromium.launch();
const page = await browser.newPage();
page.on('console', (m) => console.log('CONSOLE', m.type(), m.text().slice(0, 600)));
page.on('pageerror', (e) => console.log('PAGEERROR', e.message));
page.on('response', (r) => { if (r.url().includes('/assets/')) console.log('ASSET', r.status(), r.url().split('/').pop()); });
await page.goto(url, { waitUntil: 'networkidle' });
await page.waitForTimeout(3000);
console.log('TITLE', await page.title());
await browser.close();
